A=int(input("Qiymat kiriting A = "))
B=int(input("Qiymat kiriting B = "))
C=int(input("Qiymat kiriting C = "))
print("A ning yangi qiymati A =", C)
print("B ning yangi qiymati B =", A)
print("C ning yangi qiymati C =", B)